"""update indices and some column changes

Revision ID: 50a7a9a61304
Revises: dd9b118acd0c
Create Date: 2026-05-09 11:41:41.423516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a7a9a61304'
down_revision: Union[str, Sequence[str], None] = 'dd9b118acd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.drop_index(op.f('ix_gear_items_id'), table_name='gear_items')
    op.drop_index(op.f('ix_gear_items_name'), table_name='gear_items')
    op.create_index(op.f('ix_gear_items_category_id'), 'gear_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_gear_items_user_id'), 'gear_items', ['user_id'], unique=False)
    op.drop_index(op.f('ix_trip_items_id'), table_name='trip_items')
    op.drop_index(op.f('ix_trip_items_recorded_name'), table_name='trip_items')
    op.create_index(op.f('ix_trip_items_gear_item_id'), 'trip_items', ['gear_item_id'], unique=False)
    op.create_index(op.f('ix_trip_items_trip_id'), 'trip_items', ['trip_id'], unique=False)
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_name'), table_name='trips')
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.add_column('users', sa.Column('clerk_id', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['clerk_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'clerk_id')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.create_index(op.f('ix_trips_name'), 'trips', ['name'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.drop_index(op.f('ix_trip_items_trip_id'), table_name='trip_items')
    op.drop_index(op.f('ix_trip_items_gear_item_id'), table_name='trip_items')
    op.create_index(op.f('ix_trip_items_recorded_name'), 'trip_items', ['recorded_name'], unique=False)
    op.create_index(op.f('ix_trip_items_id'), 'trip_items', ['id'], unique=False)
    op.drop_index(op.f('ix_gear_items_user_id'), table_name='gear_items')
    op.drop_index(op.f('ix_gear_items_category_id'), table_name='gear_items')
    op.create_index(op.f('ix_gear_items_name'), 'gear_items', ['name'], unique=False)
    op.create_index(op.f('ix_gear_items_id'), 'gear_items', ['id'], unique=False)
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
